import { Product, Category } from '../types';

export const defaultCategories: Category[] = [
  {
    id: 'graphic',
    name: 'Graphic',
    slug: 'graphic',
    description: 'ক্যানভা প্রো, ফটোশপ, ইলাস্ট্রেটর ও আকর্ষণীয় গ্রাফিক্স বান্ডেল',
    imageUrl: 'https://images.unsplash.com/photo-1626785774573-4b799315345d?w=600&auto=format&fit=crop&q=80',
    sortOrder: 1,
    active: true,
    createdAt: Date.now(),
  },
  {
    id: 'video',
    name: 'Video',
    slug: 'video',
    description: 'ভিডিও এডিটিং সফটওয়্যার, প্রিসেট, টেমপ্লেট ও মোশন গ্রাফিক্স',
    imageUrl: 'https://images.unsplash.com/photo-1574717024653-61fd2cf4d44d?w=600&auto=format&fit=crop&q=80',
    sortOrder: 2,
    active: true,
    createdAt: Date.now(),
  },
  {
    id: 'bundle',
    name: 'Bundle',
    slug: 'bundle',
    description: 'অল-ইন-ওয়ান ডিজিটাল মেগা বান্ডেল ও রিসোর্স প্যাক',
    imageUrl: 'https://images.unsplash.com/photo-1550745165-9bc0b252726f?w=600&auto=format&fit=crop&q=80',
    sortOrder: 3,
    active: true,
    createdAt: Date.now(),
  },
  {
    id: 'mobile-app',
    name: 'Mobile App',
    slug: 'mobile-app',
    description: 'অ্যান্ড্রয়েড প্রিমিয়াম আনলকড ও প্রো অ্যাপস কালেকশন',
    imageUrl: 'https://images.unsplash.com/photo-1512941937669-90a1b58e7e9c?w=600&auto=format&fit=crop&q=80',
    sortOrder: 4,
    active: true,
    createdAt: Date.now(),
  },
  {
    id: 'pc-soft',
    name: 'PC Soft',
    slug: 'pc-soft',
    description: 'উইন্ডোজ, অফিস এবং প্রিমিয়াম কম্পিউটার সফটওয়্যার ও লাইসেন্স',
    imageUrl: 'https://images.unsplash.com/photo-1588702547919-26089e690ecc?w=600&auto=format&fit=crop&q=80',
    sortOrder: 5,
    active: true,
    createdAt: Date.now(),
  },
  {
    id: 'subscription',
    name: 'Subscription',
    slug: 'subscription',
    description: 'ChatGPT Plus, Canva Pro, Netflix ও প্রিমিয়াম ওটিটি সাবস্ক্রিপশন',
    imageUrl: 'https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?w=600&auto=format&fit=crop&q=80',
    sortOrder: 6,
    active: true,
    createdAt: Date.now(),
  },
  {
    id: 'tutorial',
    name: 'Tutorial',
    slug: 'tutorial',
    description: 'ডিজিটাল মার্কেটিং, গুগল অ্যাডস, গ্রাফিক্স ডিজাইন ও ফ্রিল্যান্সিং কোর্স',
    imageUrl: 'https://images.unsplash.com/photo-1516321318423-f06f85e504b3?w=600&auto=format&fit=crop&q=80',
    sortOrder: 7,
    active: true,
    createdAt: Date.now(),
  },
  {
    id: 'web',
    name: 'Web',
    slug: 'web',
    description: 'ওয়ার্ডপ্রেস থিম, প্লাগিন ও ল্যান্ডিং পেজ টেমপ্লেটস',
    imageUrl: 'https://images.unsplash.com/photo-1547658719-da2b51169166?w=600&auto=format&fit=crop&q=80',
    sortOrder: 8,
    active: true,
    createdAt: Date.now(),
  },
  {
    id: 'database',
    name: 'Database',
    slug: 'database',
    description: 'টার্গেটেড কাস্টমার ডেটাবেস, ফোন নাম্বার ও ইমেইল লিস্ট',
    imageUrl: 'https://images.unsplash.com/photo-1558494949-ef010cbdcc31?w=600&auto=format&fit=crop&q=80',
    sortOrder: 9,
    active: true,
    createdAt: Date.now(),
  },
];

export const defaultProducts: Product[] = [
  // Top Featured: 100TB Digital Product Bundle
  {
    id: 'freelancing-digital-product-business-100tb-digital-product-bundle-all-product-price-only-299',
    title: 'Freelancing Digital Product Business – 100TB Digital Product Bundle',
    slug: 'freelancing-digital-product-business-100tb-digital-product-bundle-all-product-price-only-299',
    categoryId: 'bundle',
    shortDescription: 'Freelancing Digital Product Business – 100TB Digital Product Bundle মাত্র ২৯৯ টাকা! অল-ইন-ওয়ান মেগা বান্ডেল রিসোর্স।',
    description: `🚀 Freelancing Digital Product Business – 100TB Digital Product Bundle (All Product Price Only 299 BDT)

ডিজিটাল প্রোডাক্ট সেলিং ও ফ্রিল্যান্সিং ক্যারিয়ার গড়ে তোলার জন্য ১০০ টেরাবাইট (100TB) প্রিমিয়াম ক্লাউড রিসোর্স কালেকশন!

🌟 বান্ডেলে যা যা অন্তর্ভুক্ত রয়েছে:
• গ্রাফিক্স ডিজাইন সোর্স ফাইলস (Photoshop, Illustrator, Canva Pro Templates)
• ভিডিও এডিটিং এলিমেন্টস, ট্রানজিশন, সাউন্ড এফেক্টস ও সিনেমাটিক LUTs
• প্রিমিয়াম সফটওয়্যার লাইসেন্স ও এআই টুলস গাইড
• ডিজিটাল মার্কেটিং, গুগল অ্যাডস ও ফেসবুক বুস্টিং মাস্টারক্লাস
• ১৫০০+ ওয়ার্ডপ্রেস ও এলিমেন্টর ল্যান্ডিং পেজ টেমপ্লেটস
• ১,৫০,০০০+ কপিরাইট ফ্রি রিলস ও শর্টস ভিডিও ব্যাংক
• ১০০% গুগল ড্রাইভ লাইফটাইম অ্যাক্সেস ও ইন্সট্যান্ট ডেলিভারি

📦 ডেলিভারি প্রক্রিয়া:
অর্ডার সফলভাবে পেমেন্ট করার পর সঙ্গে সঙ্গে আপনার ইমেইল ও স্ক্রিনে লাইফটাইম গুগল ড্রাইভ ডাউনলোড লিঙ্ক পৌঁছে যাবে।`,
    price: 299,
    oldPrice: 1500,
    imageUrl: 'https://images.unsplash.com/photo-1550745165-9bc0b252726f?w=800&auto=format&fit=crop&q=80',
    available: true,
    featured: true,
    newArrival: true,
    rating: 5.0,
    reviewCount: 97,
    type: 'digital',
    tags: ['bundle', '100tb', 'freelancing', 'digital product', 'resell'],
    downloadUrl: 'https://drive.google.com/drive/folders/nasir-100tb-bundle-access',
    createdAt: Date.now() - 50000,
  },

  // 1. Canva Owner Account (Featured in Screenshot 832 & 833)
  {
    id: 'canva-lifetime-owner-account',
    title: '🎯 Canva Lifetime Owner Account',
    slug: 'canva-lifetime-owner-account',
    categoryId: 'graphic',
    shortDescription: 'Canva Lifetime Owner Account – মাত্র ৪৯৯ টাকা! নিজে ব্যবহার করার পাশাপাশি Canva Access বিক্রি করে আয় করার সুযোগ।',
    description: `✅ Canva Lifetime Owner Account – মাত্র ৪৯৯ টাকা!

নিজে ব্যবহার করার পাশাপাশি Canva Access বিক্রি করে আয় করার সুযোগ।

🌟 প্রোডাক্টের প্রধান বৈশিষ্ট্য ও সুবিধাসমূহ:
• Lifetime Validity (আজীবন মেয়াদী অ্যাক্টিভেশন)
• Owner Account Access (সম্পূর্ণ অ্যাডমিন কন্ট্রোল)
• Premium Features Unlocked (সকল প্রো টেমপ্লেট ও রিসোর্স আনলক)
• সর্বোচ্চ ৫,০০০ একাউন্ট বা টিম মেম্বার যুক্ত করার সুবিধা
• ১০০% জেনুইন এবং সেফ মেথড

📦 ডেলিভারি প্রক্রিয়া:
অর্ডার সম্পন্ন করার পর দ্রুত আপনার ইমেইল বা হোয়াটসঅ্যাপে অ্যাক্টিভেশন ক্রেডেনশিয়াল এবং ইনস্টলেশন গাইড সরবরাহ করা হবে।`,
    price: 499,
    oldPrice: 1500,
    imageUrl: 'https://images.unsplash.com/photo-1626785774573-4b799315345d?w=800&auto=format&fit=crop&q=80',
    available: true,
    featured: true,
    newArrival: true,
    rating: 5.0,
    reviewCount: 38,
    type: 'digital',
    tags: ['canva', 'graphic', 'owner account', 'lifetime'],
    createdAt: Date.now() - 100000,
  },

  // 2. Google Ads Premium Course (Screenshot 832 & 833)
  {
    id: 'google-ads-premium-course',
    title: 'Google Ads Premium Course — Beginner থেকে Professional হওয়ার সম্পূর্ণ গাইড!',
    slug: 'google-ads-premium-course',
    categoryId: 'tutorial',
    shortDescription: 'গুগল অ্যাডস ক্যাম্পেইন সেটআপ, অপ্টিমাইজেশন ও কনভার্সন ট্র্যাকিং এর মাস্টারক্লাস।',
    description: `গুগল অ্যাডস এক্সপার্ট হয়ে ডিজিটাল মার্কেটিং ও ফ্রিল্যান্সিং ক্যারিয়ারে সেরা অবস্থান তৈরি করুন।

• ক্যাম্পেইন সেটআপ ও কিওয়ার্ড রিসার্চ
• কনভার্সন ট্র্যাকিং ও Google Tag Manager
• সার্চ অ্যাডস, ডিসপ্লে অ্যাডস ও ইউটিউব অ্যাডস
• লাইফটাইম অ্যাক্সেস ও সোর্স ফাইলস`,
    price: 350,
    oldPrice: 599,
    imageUrl: 'https://images.unsplash.com/photo-1551836022-d5d88e9218df?w=800&auto=format&fit=crop&q=80',
    available: true,
    featured: true,
    newArrival: true,
    rating: 4.9,
    reviewCount: 24,
    type: 'digital',
    tags: ['google ads', 'course', 'digital marketing'],
    createdAt: Date.now() - 200000,
  },

  // 3. 100+ Premium Digital Methods (Screenshot 832 & 833)
  {
    id: '100-digital-methods-bundle',
    title: 'এক কোর্সে ১০০+ প্রিমিয়াম ডিজিটাল মেথড ও প্র্যাকটিক্যাল গাইড!',
    slug: '100-digital-methods-bundle',
    categoryId: 'bundle',
    shortDescription: 'টপ রেটেড ১০০+ ডিজিটাল মেথড, সিক্রেট আর্নিং টেকনিক ও মেগা বান্ডেল রিসোর্স।',
    description: `অনলাইন বিজনেস ও ডিজিটাল ক্যারিয়ারের জন্য অত্যন্ত প্রয়োজনীয় ১০০+ মেথড ও রেডি রিসোর্স। সম্পূর্ণ ভিডিও গাইড সহ ইনস্ট্যান্ট ডাউনলোড লিঙ্ক।`,
    price: 299,
    oldPrice: 1200,
    imageUrl: 'https://images.unsplash.com/photo-1550745165-9bc0b252726f?w=800&auto=format&fit=crop&q=80',
    available: true,
    featured: true,
    newArrival: true,
    rating: 4.8,
    reviewCount: 42,
    type: 'digital',
    tags: ['bundle', 'method', 'course'],
    createdAt: Date.now() - 300000,
  },

  // 4. Aminship Survey Course (Screenshot 832 & 833)
  {
    id: 'aminship-survey-course',
    title: 'আমিনশিপ সার্ভে ৫টি কোর্স প্রো মাস্টারক্লাস!',
    slug: 'aminship-survey-course',
    categoryId: 'tutorial',
    shortDescription: 'ভূমি পরিমাপ, খতিয়ান চেনার উপায় ও জমি জমার পূর্ণাঙ্গ সার্ভে কোর্স।',
    description: `জমি ও ভূমির জটিল পরিমাপ সহজ ভাষায় শিখুন। বাস্তব প্রজেক্ট ও সরকারি নিয়মনীতি বিশ্লেষণ সহ ৫টি স্পেশাল কোর্স বান্ডেল।`,
    price: 399,
    oldPrice: 750,
    imageUrl: 'https://images.unsplash.com/photo-1581092160607-ee22621dd758?w=800&auto=format&fit=crop&q=80',
    available: true,
    featured: true,
    newArrival: true,
    rating: 4.9,
    reviewCount: 19,
    type: 'digital',
    tags: ['survey', 'land', 'tutorial'],
    createdAt: Date.now() - 400000,
  },

  // 5. Namaz Shikkha (Screenshot 833)
  {
    id: 'namaz-shikkha-guide',
    title: 'সঠিক নিয়মে নামাজ শিক্ষা — সম্পূর্ণ ডিজিটাল বুক ও গাইড',
    slug: 'namaz-shikkha-guide',
    categoryId: 'tutorial',
    shortDescription: 'সহিহ শুদ্ধভাবে নামাজ আদায়ের নিয়ম, প্রয়োজনীয় দোয়া ও মাসয়ালা সম্বলিত গাইড।',
    description: `চিত্র সহকারে সঠিক নিয়মে নামাজ আদায়ের বিস্তারিত নিয়ম ও মাসআলা। সব বয়সের মানুষের জন্য অত্যন্ত উপযোগী।`,
    price: 170,
    oldPrice: 350,
    imageUrl: 'https://images.unsplash.com/photo-1585036156171-384164a8c675?w=800&auto=format&fit=crop&q=80',
    available: true,
    featured: false,
    newArrival: true,
    rating: 5.0,
    reviewCount: 65,
    type: 'digital',
    tags: ['islamic', 'namaz', 'ebook'],
    createdAt: Date.now() - 500000,
  },

  // 6. Islamic Knowledge Library (Screenshot 833)
  {
    id: 'islamic-knowledge-mega-pack',
    title: 'ইসলামিক জ্ঞানের বিশাল ভাণ্ডার — ১০০০+ বই ও ইসলামিক রিসোর্স',
    slug: 'islamic-knowledge-mega-pack',
    categoryId: 'bundle',
    shortDescription: 'কোরআন তাফসির, হাদিস গ্রন্থ ও গবেষণামূলক ইসলামিক বইয়ের মেগা কালেকশন।',
    description: `এক ড্রাইভে ১০০০+ ইসলামিক বইয়ের দুর্লভ সংগ্রহ। আজীবন অ্যাক্সেস এবং মোবাইল ও কম্পিউটারে পড়ার সুবিধা।`,
    price: 99,
    oldPrice: 500,
    imageUrl: 'https://images.unsplash.com/photo-1564769625905-50e93615e769?w=800&auto=format&fit=crop&q=80',
    available: true,
    featured: false,
    newArrival: true,
    rating: 5.0,
    reviewCount: 88,
    type: 'digital',
    tags: ['islamic', 'books', 'pdf'],
    createdAt: Date.now() - 600000,
  },

  // 7. 150+ Landing Page Templates (Screenshot 833)
  {
    id: '150-landing-page-templates',
    title: '150+ Premium Landing Page Templates Bundle (Elementor & HTML)',
    slug: '150-landing-page-templates',
    categoryId: 'web',
    shortDescription: 'হাই-কনভার্টিং ইকমার্স ও সার্ভিস ল্যান্ডিং পেজ টেমপ্লেটস প্যাক।',
    description: `ওয়ার্ডপ্রেস Elementor এবং HTML এর জন্য তৈরি করা ১৫০টিরও বেশি প্রি-মেড হাই স্পিড ল্যান্ডিং পেজ।`,
    price: 299,
    oldPrice: 750,
    imageUrl: 'https://images.unsplash.com/photo-1460925895917-afdab827c52f?w=800&auto=format&fit=crop&q=80',
    available: true,
    featured: true,
    newArrival: false,
    rating: 4.8,
    reviewCount: 31,
    type: 'digital',
    tags: ['landing page', 'elementor', 'web design'],
    createdAt: Date.now() - 700000,
  },

  // 8. Facebook Boost Master Course (Screenshot 833)
  {
    id: 'facebook-boost-master-course',
    title: 'Facebook Boost Master Course - Zero to Hero',
    slug: 'facebook-boost-master-course',
    categoryId: 'tutorial',
    shortDescription: 'কম খরচে বেশি সেলস আনার ফেসবুক অ্যাডস ও বুস্টিং সিক্রেট মেথড।',
    description: `ফেসবুক পেইজ গ্রোথ, সেলস ফানেল ও ক্যাম্পেইন অপ্টিমাইজেশনের কমপ্লিট ভিডিও মাস্টারক্লাস।`,
    price: 299,
    oldPrice: 1200,
    imageUrl: 'https://images.unsplash.com/photo-1611162617213-7d7a39e9b1d7?w=800&auto=format&fit=crop&q=80',
    available: true,
    featured: true,
    newArrival: false,
    rating: 4.9,
    reviewCount: 47,
    type: 'digital',
    tags: ['facebook', 'ads', 'marketing'],
    createdAt: Date.now() - 800000,
  },

  // 9. Complete Visa Processing Course (Screenshot 833)
  {
    id: 'visa-processing-master-course',
    title: 'ভিসা প্রসেসিং মাস্টার কোর্স Complete Visa Processing Course',
    slug: 'visa-processing-master-course',
    categoryId: 'tutorial',
    shortDescription: 'ইউরোপ, কানাডা, আমেরিকা ও দুবাই ভিসা প্রসেসিং এর প্রফেশনাল গাইড।',
    description: `নিজে নিজেই যেকোনো দেশের স্টুডেন্ট ও ট্যুরিস্ট ভিসা প্রসেস করুন। ফাইল তৈরি থেকে এম্বাসি ফেস করার সম্পূর্ণ নির্দেশিকা।`,
    price: 299,
    oldPrice: 1500,
    imageUrl: 'https://images.unsplash.com/photo-1488646953014-85cb44e25828?w=800&auto=format&fit=crop&q=80',
    available: true,
    featured: true,
    newArrival: false,
    rating: 4.9,
    reviewCount: 52,
    type: 'digital',
    tags: ['visa', 'travel', 'course'],
    createdAt: Date.now() - 900000,
  },

  // 10. YouTube, Truecaller, CapCut (Screenshot 833)
  {
    id: 'youtube-truecaller-capcut-bundle',
    title: 'YouTube, Truecaller, and CapCut Premium All-in-One Lifetime',
    slug: 'youtube-truecaller-capcut-bundle',
    categoryId: 'subscription',
    shortDescription: 'নো অ্যাডস, প্রো ফিচার্স আনলকড অল-ইন-ওয়ান ৩টি প্রিমিয়াম অ্যাপ প্যাক।',
    description: `ক্যাপকাট প্রো, ইউটিউব প্রিমিয়াম ও ট্রুকলার গোল্ড এর আনলকড লাইফটাইম সুবিধাসম্পন্ন কম্বো প্যাক।`,
    price: 199,
    oldPrice: 500,
    imageUrl: 'https://images.unsplash.com/photo-1611162616475-46b635cb6868?w=800&auto=format&fit=crop&q=80',
    available: true,
    featured: true,
    newArrival: false,
    rating: 5.0,
    reviewCount: 73,
    type: 'digital',
    tags: ['capcut', 'youtube', 'truecaller', 'premium app'],
    createdAt: Date.now() - 1000000,
  },

  // 11. Video Editing Elements Mega Bundle (Screenshot 834)
  {
    id: 'video-editing-elements-mega-bundle',
    title: 'Video Editing Elements Mega Bundle (Transitions, LUTs & Overlays)',
    slug: 'video-editing-elements-mega-bundle',
    categoryId: 'video',
    shortDescription: 'Premiere Pro, After Effects ও CapCut এর জন্য হাজারো ট্রানজিশন ও এফেক্টস।',
    description: `সিনেমাটিক ভিডিও তৈরির জন্য প্রিমিয়াম কালার গ্রেডিং LUTs, মোশন এলিমেন্টস, টাইটেল এনিমেশন ও সাউন্ড এফেক্টস।`,
    price: 350,
    oldPrice: 2500,
    imageUrl: 'https://images.unsplash.com/photo-1574717024653-61fd2cf4d44d?w=800&auto=format&fit=crop&q=80',
    available: true,
    featured: true,
    newArrival: true,
    rating: 4.9,
    reviewCount: 39,
    type: 'digital',
    tags: ['video editing', 'transitions', 'luts'],
    createdAt: Date.now() - 1100000,
  },

  // 12. 150K Reels Bundle (Screenshot 834)
  {
    id: '150k-copyright-free-reels',
    title: '150K Copyright Free Reels Bundle (TikTok, FB, Insta, YT Shorts)',
    slug: '150k-copyright-free-reels',
    categoryId: 'video',
    shortDescription: 'কপিরাইট ফ্রি মোটিভেশনাল, গ্যাজেটস, এআই ও ভাইরাল শর্টস বান্ডেল।',
    description: `ফেসবুক পেজ ও ইউটিউব শর্টস চ্যানেল মনিটাইজ করার জন্য ১৫০,০০০+ হাই কোয়ালিটি ফুল এইচডি রিলস কালেকশন।`,
    price: 450,
    oldPrice: 450,
    imageUrl: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=800&auto=format&fit=crop&q=80',
    available: true,
    featured: false,
    newArrival: true,
    rating: 4.8,
    reviewCount: 61,
    type: 'digital',
    tags: ['reels', 'shorts', 'video'],
    createdAt: Date.now() - 1200000,
  },

  // 13. 100 GB Video Editing Bundle (Screenshot 834)
  {
    id: '100gb-video-editing-bundle',
    title: '100 GB Video Editing bundle package (Google Drive Access)',
    slug: '100gb-video-editing-bundle',
    categoryId: 'video',
    shortDescription: '১০০ জিবি হাই-স্পিড গুগল ড্রাইভ এক্সেস সহ প্রিমিয়াম ভিডিও রিসোর্স প্যাক।',
    description: `ইউটিউবার ও প্রফেশনাল ভিডিও এডিটরদের সম্পূর্ণ ড্রাইভ লাইব্রেরি। একবার ডাউনলোড করুন, লাইফটাইম ব্যবহার করুন।`,
    price: 450,
    oldPrice: 2000,
    imageUrl: 'https://images.unsplash.com/photo-1536240478700-b869070f9279?w=800&auto=format&fit=crop&q=80',
    available: true,
    featured: true,
    newArrival: false,
    rating: 5.0,
    reviewCount: 45,
    type: 'digital',
    tags: ['video', 'drive', '100gb'],
    createdAt: Date.now() - 1300000,
  },

  // 14. 30K Sound Effects (Screenshot 834)
  {
    id: '30k-sound-effects-pack',
    title: '30K Sound Effects Ultimate Pack (Studio Quality FX)',
    slug: '30k-sound-effects-pack',
    categoryId: 'video',
    shortDescription: 'কপিরাইট ফ্রি ৩০,০০০+ সিনেমাটিক ও কনটেন্ট ক্রিয়েশন সাউন্ড এফেক্টস।',
    description: `হুইসপার, হুশ, ট্রানজিশন, এক্সপ্লোশন ও ব্যাকগ্রাউন্ড অ্যাম্বিয়েন্স এর বিশাল সাউন্ড লাইব্রেরি।`,
    price: 399,
    oldPrice: 600,
    imageUrl: 'https://images.unsplash.com/photo-1511671782779-c97d3d27a1d4?w=800&auto=format&fit=crop&q=80',
    available: true,
    featured: false,
    newArrival: false,
    rating: 4.9,
    reviewCount: 22,
    type: 'digital',
    tags: ['sfx', 'sound effects', 'audio'],
    createdAt: Date.now() - 1400000,
  },

  // 15. 20K Reels with FB Auto Approve Groups (Screenshot 834)
  {
    id: '20k-reels-fb-auto-approve-groups',
    title: '20K Copyright Free Reel with Facebook auto approve group links',
    slug: '20k-reels-fb-auto-approve-groups',
    categoryId: 'video',
    shortDescription: 'ভাইরাল রিলস এবং ১০০০+ ফেসবুক অটো অ্যাপ্রুভ শেয়ারিং গ্রুপ লিস্ট।',
    description: `ফেসবুক পেজের ভিউস ও ফলোয়ার দ্রুত বাড়ানোর জন্য সিক্রেট অটো অ্যাপ্রুভ গ্রুপ ডাটাবেস সহ ২০ হাজার রিলস।`,
    price: 200,
    oldPrice: 2000,
    imageUrl: 'https://images.unsplash.com/photo-1516251193007-45ef944ab0c6?w=800&auto=format&fit=crop&q=80',
    available: true,
    featured: true,
    newArrival: false,
    rating: 4.7,
    reviewCount: 54,
    type: 'digital',
    tags: ['facebook', 'groups', 'viral'],
    createdAt: Date.now() - 1500000,
  },

  // 16. 3000 Infographics PowerPoint (Screenshot 834)
  {
    id: '3000-infographics-powerpoint-bundle',
    title: '3000 Infographics Complete Bundle PowerPoint Templates',
    slug: '3000-infographics-powerpoint-bundle',
    categoryId: 'graphic',
    shortDescription: 'বিজনেস প্রেজেন্টেশন ও চার্ট এর ৩,০০০টি এডিটেবল ইনফোগ্রাফিক স্লাইড।',
    description: `পাওয়ারপয়েন্ট, গুগল স্লাইডস ও ক্যানভায় সহজেই এডিট করা যায় এমন আকর্ষণীয় ৩০০০+ রেডি ইনফোগ্রাফিকস।`,
    price: 120,
    oldPrice: 800,
    imageUrl: 'https://images.unsplash.com/photo-1551288049-bebda4e38f71?w=800&auto=format&fit=crop&q=80',
    available: true,
    featured: false,
    newArrival: false,
    rating: 4.9,
    reviewCount: 33,
    type: 'digital',
    tags: ['infographics', 'powerpoint', 'presentation'],
    createdAt: Date.now() - 1600000,
  },

  // 17. 7000+ Bangla Design Template (Screenshot 834)
  {
    id: '7000-bangla-design-templates',
    title: '7000+ Bangla Design Template (Photoshop & Illustrator PSD/AI)',
    slug: '7000-bangla-design-templates',
    categoryId: 'graphic',
    shortDescription: 'পোস্টার, ব্যানার, লিফলেট, ভিজিটিং কার্ড ও ইসলামিক মাহফিল ব্যানার।',
    description: `বাংলাদেশের যেকোনো প্রিন্টিং ও ডিজিটাল মিডিয়া কাজের জন্য ৭,০০০+ পিএসডি ও এআই সোর্স ফাইল।`,
    price: 200,
    oldPrice: 600,
    imageUrl: 'https://images.unsplash.com/photo-1572044162444-ad60f128bdea?w=800&auto=format&fit=crop&q=80',
    available: true,
    featured: true,
    newArrival: false,
    rating: 5.0,
    reviewCount: 94,
    type: 'digital',
    tags: ['bangla design', 'psd', 'photoshop'],
    createdAt: Date.now() - 1700000,
  },

  // 18. 1500+ Excel Templates (Screenshot 834)
  {
    id: '1500-excel-templates-ready-to-use',
    title: '1500+ Excel Templates Ready to Use (Automated Business Sheets)',
    slug: '1500-excel-templates-ready-to-use',
    categoryId: 'pc-soft',
    shortDescription: 'ইনভয়েস, স্যালারি শিট, বাজেট ট্র্যাকার ও ইনভেন্টরি ম্যানেজমেন্ট এক্সেল ফাইল।',
    description: `অফিস ও ব্যবসার হিসাব-নিকাশ অটোমেট করার জন্য প্রস্তুতকৃত ১৫০০+ প্রি-ফর্মুলা যুক্ত এক্সেল টেমপ্লেট।`,
    price: 120,
    oldPrice: 400,
    imageUrl: 'https://images.unsplash.com/photo-1543286386-713bdd548da4?w=800&auto=format&fit=crop&q=80',
    available: true,
    featured: false,
    newArrival: false,
    rating: 4.8,
    reviewCount: 28,
    type: 'digital',
    tags: ['excel', 'business', 'templates'],
    createdAt: Date.now() - 1800000,
  },

  // 19. 675 GB Graphic Bundle Drive (Screenshot 834)
  {
    id: '675gb-graphic-bundle-drive',
    title: '675 GB Graphic Bundle Drive Pack (Mega Collection)',
    slug: '675gb-graphic-bundle-drive',
    categoryId: 'graphic',
    shortDescription: 'গ্রাফিক্স ডিজাইনারদের মেগা ড্রাইভ — ফন্টস, মকআপস, পিএসডি ও পিএনজি প্যাক।',
    description: `৬৭৫ জিবি গুগল ড্রাইভ ফোল্ডার এক্সেস। ফটোশপ ও ইলাস্ট্রেটরের আজীবন কাজের সব উপাদান এক ক্লিকে।`,
    price: 250,
    oldPrice: 1200,
    imageUrl: 'https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?w=800&auto=format&fit=crop&q=80',
    available: true,
    featured: true,
    newArrival: false,
    rating: 5.0,
    reviewCount: 68,
    type: 'digital',
    tags: ['graphic bundle', 'mockups', 'psd'],
    createdAt: Date.now() - 1900000,
  },
];
